#!/usr/bin/env python3

import argparse
import os
import subprocess


def main():
    path_split = os.environ["PATH"].split(os.pathsep)
    assert "./util" in path_split
    path_filtered = [path for path in path_split if path != "./util"]
    os.environ["PATH"] = os.pathsep.join(path_filtered)

    parser = argparse.ArgumentParser()
    parser.add_argument("-o", type=str, required=True)
    overwritten_args, extra_args = parser.parse_known_args()

    orig_output = overwritten_args.o
    root, ext = os.path.splitext(orig_output)
    assert ext in [".wasm", ".js"]
    output = root + ".js"

    args = ["emcc", "-o", output, "-s", "MODULARIZE=1", "-s", "ALLOW_MEMORY_GROWTH=1", "-s", "FILESYSTEM=0", "--memory-init-file=0", "-s", "ENVIRONMENT=web,worker"] + extra_args
    subprocess.check_call(args)


if __name__ == "__main__":
    main()
