#!/usr/bin/env python3

# A simple wrapper for emcc that changes the output file extension to .js

import argparse
import os
import subprocess


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-o", type=str, required=True)
    overwritten_args, extra_args = parser.parse_known_args()

    orig_output = overwritten_args.o
    root, ext = os.path.splitext(orig_output)
    assert ext in [".wasm", ".js"]
    output = root + ".js"

    args = ["emcc", "-o", output] + extra_args
    subprocess.check_call(args)


if __name__ == "__main__":
    main()
